name: reddit-job
on:
  workflow_dispatch:
  schedule:
    - cron: '20 3 * * *'  # 自定
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install praw pandas tenacity nltk google-cloud-storage google-cloud-secret-manager
      - name: NLTK cache
        run: python -c "import nltk; nltk.download('vader_lexicon')"
      - name: Run Reddit ETL
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          GCP_KEYFILE_DICT: ${{ secrets.GCP_KEYFILE_DICT }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ba882-research via GitHub Actions
        run: |
          python reddit_sentiment_job_v2.py \
            --subreddits "music,hiphopheads,popheads" \
            --start_date "2025-10-01" \
            --limit_per_query 50 \
            --time_filter year \
            --sort relevance \
            --outdir "./out"
      - uses: actions/upload-artifact@v4
        with:
          name: reddit-outputs
          path: out/*.csv
